const express = require('express');
const app = express();
const jwt = require('jsonwebtoken')
const JWT_SECRET = "randomharkirtilovekiara";
app.use(express.json());

const users =[];

// function generateToken() {
//     let options = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
//                    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
//                    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];

//                    let token ="";
//                    for(let i=0; i<32; i++) {
//                     token += options[Math.floor(Math.random() * options.length)];
//                    }
//                    return token;
// }

app.post("/signup", (req, res)=>{
    const username = req.body.username;
    const password = req.body.password;

    users.push({
        username: username,
        password: password
    })
    res.json({
        message: "you are signed in"
    })
    // console.log(users);
})

app.post("/signin", (req,res)=>{
    const username = req.body.username;
    const password = req.body.password;

    // const founduser = users.find((u)=> {
    //     if(u.username === username && u.password === password){
    //         return true;
    //     }else{
    //         return false;
    //     }
    // });  // more simple way
    let founduser = null;
    for(let i=0; i<users.length; i++) {
        if(users[i].username == username && users[i].password == password) {
            founduser = users[i];
        }
    }

    if(founduser ){
        // const token = generateToken(); //this is by using our token generator 
        const token = jwt.sign({
            username:username
        }, JWT_SECRET); // this is generated by jwt to convert it to token. which mean i convert this username into jwt token using JWT library
        // we don't need to store it to database. In jwt this "token" is stateless which mmeans it can store it's states itself
         res.json({
            message:token
         });  // this is stateless 
    }else{
        res.status(403).send({
            message: "Invalid username or password"
        })
    }
    // console.log(users);
})
//how to copy someone whole browsser code and bring it to my local machine
app.get("/me", (req, res)=> {  // this part is for Authenticated end point  that is the user are authenticated or not  
    const token = req.headers.token;
    
    const decodedInformation = jwt.verify(token, JWT_SECRET);  // this line return the json {username: "harkirt"}

    const username = decodedInformation.username;
console.log("aaya hai !")
    let  foundUser = users.find((u)=> {
        if(u.username == username){
            return true;
        }else{
            return false;
        }
    })
    if(foundUser){

        res.json({
            username:foundUser.username,
            password:foundUser.password
        })
    }else{
        res.json({
            message:"user not found",
        })
    }
})

app.listen(3001);